### ISSUE TITLE
Inserting an all-day task with DURATION, but without TZ fails with NullPointerException

### ISSUE THREAD

**Issue by rfc2822** [dmfs/opentasks-provider#5]
Hello,

When inserting an all-day task with `DURATION`, but without `TZ`, opentasks-provider throws `java.lang.NullPointerException: timezone is null!`

Inserted task:

```
[ mType: 2,
mUri: content://org.dmfs.tasks/tasks/163?account_name=test%40test.com&account_type=bitfire.at.davdroid&caller_is_syncadapter=true,
mSelection: null,
mExpectedCount: null,
mYieldAllowed: false,
mValues: [
  percent_complete=0
  duration=PT10M
  dtstart=1452297600000
  title=Test_Task
  status=0
  location=null
  priority=5
  description=null
  is_allday=1
  class=0
  url=null
],
mValuesBackReferences: null,
mSelectionArgsBackReferences: null ]
```

It works when `TZ` is set, like here:

```
[ mType: 2,
mUri: content://org.dmfs.tasks/tasks/163?account_name=test%40test.com&account_type=bitfire.at.davdroid&caller_is_syncadapter=true,
mSelection: null,
mExpectedCount: null,
mYieldAllowed: false,
mValues: [
  percent_complete=0
  duration=PT10M
  dtstart=1452297600000
  title=Test_Task
  tz=Europe/Vienna   ##### !!!!! #####
  status=0
  location=null
  priority=5
  description=null
  is_allday=1
  class=0
  url=null
],
mValuesBackReferences: null,
mSelectionArgsBackReferences: null ]
```

According to the docs, `TZ` may be null (which makes sense for all-day events).

For further information and the original VTODO see: https://forums.bitfire.at/topic/929/timezone-is-null/

**Comment by dmfs** [comment]
Yeah, Android's Time class doesn't support floating times. We've already rewritten the entire part for version 1.1.8 and ditched the Time class in favor of our own DateTime. The NPE should be history with the upcoming release.

However, note that your Task insert will still fail because you're trying to insert an all-day task with a duration of 10 minutes. The current version happily accepts this, but I think the new version won't.

Please open a new issue if still see this issue in the upcoming version 1.1.8
